### ISSUE TITLE
can pedigree information be fed into SHAPEIT5?

### ISSUE THREAD

**Issue by cdquinto** [odelaneau/shapeit5#10]

**Comment by JosephLalli** [comment]
Yes - the --pedigree options allows for the consideration of pedigrees of format ChildID\tFatherID\tMotherID

See input files section of SHAPEIT5_common documentation:
https://odelaneau.github.io/shapeit5/docs/documentation/phase_common/

**Comment by cdquinto** [comment]
Great, thanks!
