### ISSUE TITLE
Needs of AVX2

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/shapeit5#13]
Hi,

As I'm working on the integration of SHAPEIT5 in nf-core, I was wondering which modules of SHAPEIT5 needs AVX2 to work.
Unfortunately their is no fallback possible in your code to run SHAPEIT5 and GLIMPSE2 on host without the AVX2 feature available.

So I added some test in the nf-core process to check if AVX2 is available or not, before running.

Could you tell me which functions needs AVX2 ?
phase_rare and phase_common seems to need it.

Thanks

**Comment by odelaneau** [comment]
Yes both phase_rare and phase_common need AVX as HMM computations are easy to vectorize. AVX is available on all CPU since 2012 and speeds up analyses so much that it would be such a waste to not use it. Is there any way to use AVX in nf-core?
