### ISSUE TITLE
How to fix 'make" problem

### ISSUE THREAD

**Issue by jpbreed90** [odelaneau/shapeit5#16]
Hi. I have used shapeit4, and have been using it well without any problems.
In order to use another data set this time, I access the homepage of shapeit4 and see the message to use shapeit5, so I am installing it.
I modified the path of HTSSRC, BOOST in each tool's makefile file, and replaced the makefile of all tools. Then, when executing the "make" command, the following error occurs.

"make: *** No rule to make target `src/containers/bitvector.h', needed by `obj/haplotype_writer.o'.  Stop."
or
"make -C phase_common
make[1]: *** No rule to make target `src/containers/bitvector.h', needed by `obj/haplotype_writer.o'.  Stop.
make: *** [phase_common] Error 2"

There was no problem using shapeit4, but shapeit5 has not been installed since.
I'm using the Macbook Pro Ventura version.
How can we solve this problem?

**Comment by jikhashkya** [comment]
Having the same issue, it looks like `bitvector.h` actually has a symbolic link to the actual file which is supposed to be in `xcftools` folder but when git cloning the repo, the directory is just empty. In any case, you can try downloading the static binary file, convert the file to be an executable file like so `chmod +x <static_file_name>`.

**Comment by odelaneau** [comment]
I see the problem, it's indeed related to the symlink. I'll solve it asap.
In the meantime, try to clone xcftools to get bitvector class. It's a
submodule.

Olivier.

Le lun. 3 avr. 2023, 07:50, Pramesh Shakya ***@***.***> a
écrit :
