### ISSUE TITLE
multi-allelic sites defaults supported？

### ISSUE THREAD

**Issue by octpus616** [odelaneau/shapeit5#17]
Hi, 
Thanks for development shapeit5, I know that shapeit is a widely recognized phased software, but earlier versions of shapeit such as shapeit2 don't seem to accept multi-allelic sites. Has the lastest version of shapeit5 added this support?

Regrads
Zhang

**Comment by odelaneau** [comment]
Nop, you should use bcftools norm before processing multi-allelic sites in
order to decompose multi-allelic into a series of bi-alleleic.

Hope that helps,

Olivier Delaneau

**Comment by octpus616** [comment]
Hi，@odelaneau 
Thanks for your reply, I have an additional question. The vcf may contain many lines with one same position if there is a multi-allelic siites. Is shapeit5 can accpected this? or I need to do someting more?

**Comment by odelaneau** [comment]
S5 uses position, REF and ALT to uniquely identify variant sites. So,
having multiple sites at the same position is not an issue as long as they
do not share the same REF and ALT alleles.

Olivier Delaneau

**Comment by octpus616** [comment]
Hi, @odelaneau
Thank you for your kind help. I appreciate your time and effort in solving my problem. I have learned a lot from your explanation. You are awesome! 
Please allow me for having an extra question that is unrelated to this topic, so I opened another issue. I will close this issue, thank you again for your help.
