### ISSUE TITLE
Whats the source of genetic map (GRCh38)?

### ISSUE THREAD

**Issue by octpus616** [odelaneau/shapeit5#18]
Hi, 
Thanks for your published a well prepared genetic map for GRCh38.
I am a bit confusing about this resources, as I know, there is a very old source of orginal hapmap genetic map (Its based on b35 and liftover to GRCh37) [geneticMap-GRCh37](https://github.com/adimitromanolakis/geneticMap-GRCh37), and 1kg project seems to be following this version (with some additional updates for some groups) [1000-genomes-genetic-maps](https://github.com/joepickrell/1000-genomes-genetic-maps). So there seem to be some different sources here. Could you please share some additional clarification about the source of the attached gentic map?

Moreover, if this file was gradually liftover from the original b35 version, can I further liftover this file if I wish to do some work based on a newer reference genome (such as CHM13)? Will this bring some negative effects?

Please feel free to correct me if I'm wrong.

Regrads
Zhang

**Comment by odelaneau** [comment]
For the source, I'll have to dig as I have been using these files for quite a while now.
I think you can lift them over as errors in this file will not have a dramatic impact on phasing.
Assuming a constant recombination rate is already working pretty well. These files basically add an additional accuracy boost for small sample sizes.

**Comment by zhangpicb** [comment]
Hi @odelaneau @octpus616 

Sorry to reopen this issue.

YRI,CEU or EAS population using the same genetic map files are reasonable? 
I am a new one about PHASING GENOTYPE.

Thanks in advanced!
