### ISSUE TITLE
Question about reproducibility

### ISSUE THREAD

**Issue by koido** [odelaneau/shapeit5#25]
Hi,

Thanks for developing such an excellent tool.

I noticed that if I want to make the `phase_common` results reproducible, I have to use a single thread (and keep the seed, although the default seed is fixed).
This was described in the SHAPEIT4's document as follows: 
> 10. Reproducibility
> Making reproducible runs can sometimes be useful. To do so, you need to specify the random generator seed using --seed and to use a single thread. Using multi-threading prevents reproducibility.

Regarding `ligate` and `phase_rare`, should I use a single thread to make it reproducible?

Although I want to use multiple threads to speed up, I am also concerned about reproducibility and its potential effects on my downstream analysis.

Best,

**Comment by odelaneau** [comment]
Hi Masuru,

I think ligate and phase_rare are safe, there's no random sampling in
there.
Multi-threading and reproducibility should be possible.

But as you mention; this is not the case for phase_common.

Cheers;

Olivier Delaneau


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le ven. 21 avr. 2023 à 06:13, Masaru Koido ***@***.***> a
écrit :

**Comment by koido** [comment]
Hi Olivier,

Thank you very much for your helpful response.

Best,
Masaru
