### ISSUE TITLE
Avg phaseQ value in usage document

### ISSUE THREAD

**Issue by koido** [odelaneau/shapeit5#27]
Hi Olivier,

I found a potential inconsistency between the Avg phaseQ value in the usage and the actual values observed in the logs.

[The Documentation](https://odelaneau.github.io/shapeit5/docs/documentation/ligate/) states, "We usually expect values above 0.8 or even 0.9." However, I noticed that my actual log values are much larger (over 90).

Upon examining [the code](https://github.com/odelaneau/shapeit5/blob/51bd862d157145fc38940699e8f769a15fc8b02f/ligate/src/ligater/ligater_algorithm.cpp#L198), the phaseQ calculation appears to produce values in the range of 0 to 99.

I suspect the description of the phaseQ value range might be "above 80 or even 90" instead of "0.8 or even 0.9."
Is my interpretation correct?

I'm using v5.1.0.

Many thanks again.

Best,
Masaru

**Comment by odelaneau** [comment]
Thanks for spotting this. I updated the documentation accordingly.

**Comment by koido** [comment]
Many thanks for the update!
