### ISSUE TITLE
Installation error in make process

### ISSUE THREAD

**Issue by BIOJHK** [odelaneau/shapeit5#28]
Hello, I used shapeit4 in last year, but I want to use shapeit5 also.
When I do shapeit5 installation process, fatal error popped up and cosuming my time...
I'm working with this version,

(base) jhk0709@R750xs:~/Public/230424/shapeit5/phase_rare$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

and Centos also. (I will install shapeit5 in Centos later when this error solved and successfully installed.)

Make error occurred here.. 
/home/jhk0709/Public/230424/htslib/hfile_s3_write.c:859: undefined reference to `curl_global_init'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:866: undefined reference to `curl_share_init'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:874: undefined reference to `curl_share_setopt'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:875: undefined reference to `curl_share_setopt'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:876: undefined reference to `curl_share_setopt'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:885: undefined reference to `curl_version_info'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:879: undefined reference to `curl_share_cleanup'
/usr/bin/ld: /home/jhk0709/Public/230424/htslib/hfile_s3_write.c:880: undefined reference to `curl_global_cleanup'
/usr/bin/ld: /usr/local/lib/libhts.a(hfile_s3_write.o): in function `s3_write_exit':
/home/jhk0709/Public/230424/htslib/hfile_s3_write.c:831: undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
make: *** [makefile:129: bin/phase_rare] Error 1

when I install with htslib, it doesn't process well so I check link all *c file - and same error message popped up!
(base) jhk0709@R750xs:~/Public/230424/htslib-1.17$ gcc hfile_s3_write.c -lcurl
hfile_s3_write.c:67:10: fatal error: config.h: No such file or directory
   67 | #include <config.h>
      |          ^~~~~~~~~~
compilation terminated.

when I found the message for your installation guide, when the htslib successfully done with make process, 
it has no libhts.a (so I make link with ln -s to /usr/local/lib/) 
and CPATH to solve htslib and samtools.

What can I do for solve this make solution?

**Comment by odelaneau** [comment]
Hi,

There are static bins and a docker available.
Try to use them, no need to recompile.

Best,

O

**Comment by BIOJHK** [comment]
Oh, thank you for quick reply!
I'm not the friend of docker, so I just download static bins to install shapeit5.
Well, I expected shapeit5.sh in static bins file... but it doesn't existed anywhere...
bin and obj file was empty, src file has cpp / h format files.

(base) jhk0709@R750xs:~/Public/230424/shapeit5-5.1.0/phase_common$ ls bin/

(base) jhk0709@R750xs:~/Public/230424/shapeit5-5.1.0/phase_common$ ls obj/

(base) jhk0709@R750xs:~/Public/230424/shapeit5-5.1.0/phase_common$ ls src/
containers  io  main.cpp  models  modules  objects  phaser  utils

Is it right that I just download and using shapeit5 immediately? 
It may be do some process needed.. like make...

and I remember in shapeit4, installation process is need to write path for confirmmation(is it right? I can't remember exact words) like,
hstlib=/directory/to/hstlib
boost=/directory/to/boost

but in shapeit5 guide to do just 'make'. 
Could I get the information of default directory for doing successfuly 'make command'?

Thank you.

**Comment by BIOJHK** [comment]
Oops. I found the solution.
I didn't do edit any makefile for succesfully done... 
Thank you for help with fast answer!

**Comment by odelaneau** [comment]
Just download the static binaries in the v5.1.1 pre-release.
No need to re-compil, etc ...
There's a link on the right hand side of the github page.

**Comment by BIOJHK** [comment]
Oh, thank you for updated information. I just downloaded and check the program works well.
