### ISSUE TITLE
phase_common is removing all variants

### ISSUE THREAD

**Issue by williamscole** [odelaneau/shapeit5#29]
Hello– I'm running phase_common and it is removing all my sites (says that they are multi-allelic) and then exits because there are no variants to phase. This is commit 5cc58e4 (4 Apr 2023). I also have phase_common from commit 1d357ac (2 Feb 2023) compiled and it successfully phases the same vcf. Any idea what's going on here?

Edit: I saw another post with the same problem where you had them post the output of `bcftools view -G -H [vcf]`. Here are the first few lines of that output (and I can attach the whole file if needed)
<img width="612" alt="image" src="https://user-images.githubusercontent.com/47306731/235998082-f1473884-d513-444a-8c2d-732273e59cd5.png">

**Comment by odelaneau** [comment]
Hi,

Could you check if the v5.1.1 pre-release if fixing your problem?

Best

**Comment by williamscole** [comment]
Sorry for the delayed response. Everything works perfectly now. Thanks!
