### ISSUE TITLE
phase_common_static：ERROR: Opening [1Z.vcf]: unknown error

### ISSUE THREAD

**Issue by yangwukaidi** [odelaneau/shapeit5#32]
hi，dear Delaneau.
Sorry to bother you, I have a problem with phase_common that bothers me.
as follows:

[root@localhost LD-Decay]# docker run shapeit5_2023-03-23_a4a1818 phase_common_static -I 1Z.vcf -R 1 -O shapeitphase_1Z.vcf --thread 6
[SHAPEIT5] phase_common (jointly phase multiple common markers)
  * Author        : Olivier DELANEAU, University of Lausanne
  * Contact       : olivier.delaneau@gmail.com
  * Version       : 5.1.0 / commit = 492781e / release = 2023-04-13
  * Run date      : 15/05/2023 - 14:17:53
Files:
  * Input         : [1Z.vcf]
  * Output        : [shapeitphase_1Z.vcf]
  * Output format : [bcf]
Parameters:
  * Seed    : 15052011
  * Threads : 6 threads
  * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
  * PBWT    : [window = 4cM / depth = auto / modulo = auto / mac = 5 / missing = 0.1]
  * HMM     : [window = 4cM / Ne = 15000 / Constant recombination rate of 1cM per Mb]
Reading genotype data:
[E::hts_open_format] Failed to open file "1Z.vcf" : No such file or directory
ERROR: Opening [1Z.vcf]: unknown error

I'm pretty sure 1Z.vcf is in the current running directory. But these errors still occur.
I still have this problem when I try to add absolute paths.
How can I solve this problem?
Looking forward to your reply!

**Comment by odelaneau** [comment]
Right-hand side of the GitHub page, there's the "release" panel.
You'll find there precompiled static binaries.
Try using them instead of the docker.
That might be easier.

**Comment by selasphoruskershaw** [comment]
Hello,

I am getting the same error as the original poster. My unphased vcf is in the current directory, but shapeit is saying it's not there: ERROR: Opening [NC_053450.1.vcf.gz]: unknown error
[E::hts_open_format] Failed to open file "NC_053450.1.vcf.gz" : No such file or directory

I am using the following command: docker run shapeit5_2023-05-05_d6ce1e2 phase_common_static --input NC_053450.1.vcf.gz --region NC_053450.1 -O NC_053450.1.phased

I have been unable to compile from source or to use the precompiled static binaries.

Please help, thank you.

**Comment by odelaneau** [comment]
By default, containers cannot see the file system of their host.

Please read about docker or use static binaries.
