### ISSUE TITLE
Does phase_common use phase sets in WGS-derived VCF files?

### ISSUE THREAD

**Issue by fwplace** [odelaneau/shapeit5#39]
Hello, Thank you for providing this wonderful tool. I am currently working with VCF files that have phased genotypes on certain variant sites when they are close. The majority of variants in the VCF files are unphased, while only a small portion are phased by GATK. I have noticed that shapeit4 can utilize the phase sets from the `PS` field in VCF files. Since phase_common has replaced shapeit4, I am wondering if it can also make use of this phasing set information.

**Comment by odelaneau** [comment]
Sorry about this. It's one of the functionality I have not yet moved to S5 and tested. If you want to use PS, please use S4. Thanks.
