### ISSUE TITLE
ERROR: Opening [info/target.haploid.txt]: file format not supported by HTSlib

### ISSUE THREAD

**Issue by Ilaria-Pirona** [odelaneau/shapeit5#42]
Good morning,
I am trying to use your program using the data in the test folder. Following the commands present in phasing chromosome X data ([link](https://odelaneau.github.io/shapeit5/docs/documentation/phase_common/)) and using the container [quay.io/biocontainers/shapeit5:1.0.0--h0c8ee15_0](http://quay.io/biocontainers/shapeit5:1.0.0--h0c8ee15_0) I get the following error:

SHAPEIT5_phase_common --input array/target.haploid.bcf --reference info/target.haploid.txt --region 1 --map info/chr1.gmap.gz --output target.phased.bcf  --thread 8

ERROR: Opening [info/target.haploid.txt]: file format not supported by HTSlib

Can you help me figuring out which is the problem?
Thank you

**Comment by theandyb** [comment]
It looks like you're passing the list of haploids to the `--reference` option and not the `--haploids` option as it is written in the tutorial. The error is in response to the program expecting a VCF/BCF file to be passed as the reference option (as is done in the 4th usage example).
