### ISSUE TITLE
where to download liftovervcf_static?

### ISSUE THREAD

**Issue by WeiCSong** [odelaneau/shapeit5#44]
Hi,
 it seems that your release page is updated and the loftovervcf tool mentioned in the tutorial is not found in the release page. Could you update the release page for this tool? Also, sine I'm running on local machine instead of dnanexus, I wonder there would be executable rather than a docker image. Thanks for your help!

**Comment by RJHFMSTR** [comment]
Hi,

We only have the docker image available for now (here:https://github.com/odelaneau/shapeit5/releases/download/v1.0.0/liftovervcf_0.0.1.tar.gz) as described here: https://odelaneau.github.io/shapeit5/docs/tutorials/ukb_snp_array/

You can use the main repository for the liftover tool is you want to compile it by yourself (https://github.com/odelaneau/otools/tree/main)

Best,
Robin
