### ISSUE TITLE
Genetic map file for T2T genome (CHM13)

### ISSUE THREAD

**Issue by hangsuUNC** [odelaneau/shapeit5#54]
Hi,

Thanks for this wonderful tool! I was trying to use Shapeit5 for phasing a set of samples processed based on the new released T2T human genome (CHM13). Could you please help pointing the right genetic mapping files? I can only find b37 and b38 genomes in the folder.

Thanks very much for your help!

Hang

**Comment by srubinacci** [comment]
Hi,

We do not have T2T maps available in this repo yet, but you can liftover the provided maps to the T2T reference. 
I have also seen a publicly available [github repo](`https://github.com/JosephLalli/phasing_T2T/tree/master`) made by Joseph Lalli providing lifted over maps. Just, before using them, please make sure with Joseph you are allowed to.

Simone

**Comment by hangsuUNC** [comment]
Thanks for the information! This is very helpful! will do!

> Hi,
> 
> We do not have T2T maps available in this repo yet, but you can liftover the provided maps to the T2T reference. I have also seen a publicly available github repo (https://github.com/JosephLalli/phasing_T2T/tree/master) maintained by Joseph Lalli providing lifted over maps. Just, before using them, please make sure with Joseph you are allowed to.
> 
> Simone
