### ISSUE TITLE
"Wrong order in your genetic map file" in concatenated genetic files

### ISSUE THREAD

**Issue by chunxuan-hs** [odelaneau/shapeit5#59]
I am trying to phase a trios dataset (only three samples, offspring, father, mather).  I dowloaded the tar.gz file of hg38 genetic maps in the resource folder, unzipped it and concatenated all files (execpt X) to a single file. 

However, I glot the following error, 
`ERROR: Wrong order in your genetic map file 248924793bp / 286.27923cM > 12994bp / 0.00000cM`

It turns out the position locates at the end of chr1.

> 248924793       1       286.279234
> 12994   2       0
> 15491   2       0.000848
> 15672   2       0.000908 

How to specify the genetic files correctly, and is a concatenated file including all chr allowed?

My codes:
```
#- Genetics maps of all chrome
path_map="genetic_map_hg38_shapeit5.gz"
phase_common --input $path_vcf \
    --pedigree $path_fam  \
    --reference $path_ref \
    --region 22 \
    --thread 8 \
    --map $path_map \
    --output test.vcf.gz
```

Many thanks!

**Comment by srubinacci** [comment]
Hi,

The map files are not meant to be concatenated or unzipped. Just pass the correct map file to the software according to the chromosome you are phasing.

Simone

**Comment by srubinacci** [comment]
You did not do anything wrong. We remove these tags because we would need to store them in memory the whole time otherwise.
If you need them back, you can use bcftools annotate to reannotate your file.

Simone

**Comment by chunxuan-hs** [comment]
Thanks for the quick reply, bcftools worked well!
