### ISSUE TITLE
Phasing with relateds as scaffold

### ISSUE THREAD

**Issue by psnavais** [odelaneau/shapeit5#60]
Hi! 

We have a large dataset of related samples (>40K trios, >20K duos) and many more samples that are unrelated. So far, we are phasing related samples using the `--pedigree` flag. When it comes to phasing the rest of unrelated samples (using the previously phased related samples as scaffold), I have two questions:
1. Do we need to include the related samples in this set as well?
2. If so, do we have to include the `--pedigree` flag as well?

I will be phasing in chunks, I imagine this doesn't affect the "pipeline", except for the ligate step. 

Huge thanks for the time and for the neat documentation.

Best,
Pol

**Comment by srubinacci** [comment]
Hi,

Not sure I understand what you mean by "using the previously phased related samples as scaffold". Do you mean reference panel?

In general, if possible, I would phase everyone together without proceeding in two steps. More samples you phase together, better the phasing is. You just need to specify parental relationships in the pedigree file for the samples who have them.

Hope this helps

Simone

**Comment by psnavais** [comment]
That was helpful, thanks!

I got confused by the definition of scaffold. From the documentation I understood that if you had a good set of haplotypes (in our case, those coming from related individuals), then you can use these as a scaffold to phase other samples.
