### ISSUE TITLE
fasta file format not supported

### ISSUE THREAD

**Issue by suvi93** [odelaneau/shapeit5#61]
Hi, 

I'm using SHAPEIT5 and I'm getting this error - 
`ERROR: Opening [ref.fasta]: file format not supported by HTSlib`

the command I'm using is as follows - 
`SHAPEIT5_phase_common -T 16 -I S2_WhPh.vcf.gz -H ref.fasta -R PGA_scaffold_6 -O S2_SH.vcf --log P24XYF_S2_SH.log`

what does this error mean exactly?

Thanks!

**Comment by srubinacci** [comment]
Hi,

When refer to "reference panel" we mean a cohort of haplotypes (e.g. in vcf/bcf format), not the reference genome sequence (in fasta). You are simply providing a wrong file. 

You can find some common definitions here, in the hope they are useful: https://odelaneau.github.io/shapeit5/docs/glossary/#reference-panel

Hope this helps,

Simone

**Comment by srubinacci** [comment]
Hi,
Unfortunately, population-based statistical phasing needs at least a certain amount of samples to be reliable. 

Simone
