### ISSUE TITLE
Phase_ rare_static Error: 31mERROR: [0mNo variants to be phased!

### ISSUE THREAD

**Issue by hangsuUNC** [odelaneau/shapeit5#63]
Hi,

I was running phase_rare_static on a merged vcf files. While running, it gives an error`[31mERROR  [0mNo variants to be phased!` when reading the genotype data.

```
[SHAPEIT5] Phase_rare (phase rare variants onto a haplotype scaffold)
* Authors : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
* Contact : simone.rubinacci@unil.ch & olivier.delaneau@gmail.com
* Version : 5.1.1 / commit = 990ed0d / release = 2023-05-08
* Run date : 29/09/2023 - 20:32:10

Files:
* Unphased data : [tmp.out.bcf]
* Scaffold data : [tmp.scaffold.bcf]
* Genetic Map : [/cromwell_root/fc-secure-f7d80b48-be60-426f-aa6b-f037a1bf7f34/scratch/hangsu/chr6.t2t.gmap.resorted.gmap.gz]
* Output data : [shapeit5_all_variants_phased.bcf]

Parameters:
* Seed : 15052011
* Threads : 16 threads
* PBWT : [depth = 2,2 / modulo = 0.1 / mac = 2 / mdr = 0.1]
* HMM : [Ne = 15000 / Recombination rates given by genetic map]

Parsing specified genomic regions
* Scaffold region [6:100096734-131496019]
* Input region [6:100096734-131496019]

Reading genotype data
[31mERROR: [0mNo variants to be phased!
```

It seems that the program is not able to read in the genotype data. Or is it because there is no variants to be phased in the vcf file?

Your input is appreciated!

Thanks,

Hang

**Comment by srubinacci** [comment]
Hi,
Thanks for this. Difficult to say what's wrong. Of course the obvious suggestion is to look at the "tmp.out.bcf" file, as it seems it does not have "new" variants to be phased in the region. Maybe try to intersect with tmp.scaffold.bcf and print a list of variatns that are private to tmp.out.bcf (e.g. with bcftools isec).

Simone

**Comment by karinkumar** [comment]
Hello I'm having the same issue @hangsuUNC  how did you solve this?

**Comment by hangsuUNC** [comment]
> Hello I'm having the same issue @hangsuUNC how did you solve this?

Hi sorry just saw this message. If I recall correctly, the input file is fully phased so nothing needs to be phased in the program. That's why the issue occurs.

Hope this helps!

Hang
