### ISSUE TITLE
phase_common: command not found

### ISSUE THREAD

**Issue by aissushan** [odelaneau/shapeit5#64]
Hi everyone, I tried running the documentation part of SHAPEIT5 but unfortunately when I run the phase common code, it says command not found: phase_common --input array/target.unrelated.bcf --region 1 --map info/chr1.gmap.gz --output target.phased.bcf --thread 8
phase_common: command not found

I tried running these lines of codes, but still error, although the phase common package is listed when I run ls -a:

aissu98@asvryxx:~/shapeit5/test$ sudo apt install phase_common
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package phase_common
aissu98@asvryxx:~/shapeit5/test$ cd ../
aissu98@asvryxx:~/shapeit5$ ls -a
.        docker       LICENSE       phase_rare  .settings    tasks
..       docs         ligate        README.md   simulate     test
archive  .git         makefile      resources   static_bins  versions
common   .gitmodules  phase_common  scripts     switch       xcftools

**Comment by srubinacci** [comment]
You first need to download the executable here: https://github.com/odelaneau/shapeit5/releases/tag/v5.1.1
Then, simply use "./phase_common_static" using the file you just downloaded.

**Comment by aissushan** [comment]
> You first need to download the executable here: https://github.com/odelaneau/shapeit5/releases/tag/v5.1.1 Then, simply use "./phase_common_static" using the file you have just downloaded.

Hi, thank you for the suggestion. I have tried doing it but it is still unsuccessful. I am currently running the UBUNTU on a virtual machine in my MacOS. Could that be the reason?

**Comment by pettyalex** [comment]
@aissushan Are you on an Apple Silicon Mac? M1 or M2 processor? shapeit 5 only supports Intel or AMD processors.

**Comment by aissushan** [comment]
> @aissushan Are you on an Apple Silicon Mac? M1 or M2 processor? shapeit 5 only supports Intel or AMD processors.

hi, yeap I am on M1 processor. I see, ok thank you, will try to use another computer for this

**Comment by aissushan** [comment]
@pettyalex yeap I am on M1 processor. I see, okay thank you. I will try to run it on a different computer
