### ISSUE TITLE
AAscore software

### ISSUE THREAD

**Issue by nathanLauHKGI** [odelaneau/shapeit5#73]
Are there any existing software to get AAscore for a VCF file?

It is mentioned in the following paper:
Statistical phasing of 150,119 sequenced genomes in the UK Biobank

Thank you

**Comment by rwk-unil** [comment]
The AAscore is given by GraphTyper
GitHub : https://github.com/DecodeGenetics/graphtyper
Refer to their manual : https://github.com/DecodeGenetics/graphtyper/wiki/User-guide#snp-and-indel-filtering

see" The sequences of 150,119 genomes in the UK Biobank" paper "SNP and Indels" section, link : https://www.nature.com/articles/s41586-022-04965-x#Sec2 it describes that the AAscore comes from GraphTyper for the 150,119 sequenced genomes in the UK Biobank.
