### ISSUE TITLE
Phasing of small parent-offspring sample

### ISSUE THREAD

**Issue by friedav** [odelaneau/shapeit5#82]
Dear SHAPEIT5 team,

for the genotype imputation (common variants) of a small sample of 133 mother-offspring duos (total n=266) from SNP array data, I am wondering if it is better to perform phasing based on

- [Usage2 (phasing related samples)](https://odelaneau.github.io/shapeit5/docs/documentation/phase_common/#usage2-phasing-related-samples) with the `--pedigree` option
- [Usage4 (phasing using a reference panel)](https://odelaneau.github.io/shapeit5/docs/documentation/phase_common/#usage4-phasing-using-a-reference-panel) with the `--reference` option

Or is it possible (and helpful) to combine both?

Thank you for any recommendations.
Best,
Friederike

**Comment by RJHFMSTR** [comment]
Hi Friederike,

The `--pedigree` option allows you to have an accurate phasing of offsprings, but not mothers.
Depending on your needs, I would advice to use both.

Best,
Robin
